# Project Euler - Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.


def fibonacci_nums(upper_limit):
    # Initialize a, b variables as first two number of fib sequence.
    a, b = 1, 1
    # Set total variable equal to 0.
    total = 0
    # While a is less than the given limit, if a is an even, add a to the number stored in the total.
    while a < upper_limit:
        if a % 2 == 0:
            total += a
        # Move the variables to the next numbers in the sequence. ex. 1, 2 = 2, 1+2.
        a, b = b, a + b
    return total
        
                  
print(fibonacci_nums(4000000))